apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-users
  template:
    metadata:
      labels:
        app: api-users
    spec:
      containers:
      - name: container-api-users
        image: viniciusdelr/users-service:latest 
        imagePullPolicy: Always 
        ports:
        - containerPort: 80 
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
---
apiVersion: v1
kind: Service
metadata:
  name: servico-api-users
spec:
  type: ClusterIP 
  selector:
    app: api-users
  ports:
  - protocol: TCP
    port: 80      
    targetPort: 80 